# Configuration for support-requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: "Support request"
# Comment to post on issues marked as support requests. Add a link
# to a support page, or set to `false` to disable
supportComment: >
  Thanks, but this issue tracker is not intended for support requests. Please read the guidelines on [submitting an issue](https://github.com/jasonwynn10/MyPlot/blob/master/CONTRIBUTING.md#creating-an-issue).


  [Docs](https://github.com/jasonwynn10/MyPlot/wiki) | [Discord](https://discord.gg/qqcpp9q) | [Forums](https://forums.pmmp.io)

# Whether to close issues marked as support requests
close: true
# Whether to lock issues marked as support requests
lock: false