diff --git a/.codeclimate.yml b/.codeclimate.yml
index e69de29..e676d61 100644
--- a/.codeclimate.yml
+++ b/.codeclimate.yml
@@ -0,0 +1,24 @@
---
engines:
  duplication:
    enabled: true
    checks:
      Identical code:
        enabled: false
      Similar code:
        enabled: false
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/LongVariable:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
ratings:
  paths:
  - "**.php"
  - "**.yml"
exclude_paths: []
