approve_by_comment: true
approve_regex: '^(A|a)pproved|\+1'
reject_regex: '^(R|r)ejected|-1'
reject_value: -1
reset_on_push: false
reviewers:
  members:
  - jasonwynn10
  name: pullapprove
  required: 1
