name: MyPlot
main: MyPlot\MyPlot
version: 1.1
load: STARTUP
api: [1.13.0, 2.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
author: Wies, Exxarion, and jasonwynn10
description: Plot and protection plugin
softdepend: [EconomyAPI, PocketMoney]

permissions:
  myplot.command:
    description: Allows users to use myplot features
    default: op
    children:
      myplot.command.help:
        description: Displays all the available commands
        default: true
      myplot.command.claim:
        description: Gives the claim command
        default: true
      myplot.command.info:
        description: Gives the info command
        default: true
      myplot.command.generate:
        description: Gives the generate command
        default: op
      myplot.command.addhelper:
        description: Gives the addhelper command
        default: true
      myplot.command.removehelper:
        description: Gives the removehelper command
        default: true
      myplot.command.auto:
        description: Gives the auto command
        default: true
      myplot.command.clear:
        description: Gives the clear command
        default: true
      myplot.command.dispose:
        description: Gives the dispose command
        default: true
      myplot.command.reset:
        description: Gives the reset command
        default: true
      myplot.command.home:
        description: Gives the home command
        default: true
      myplot.command.homes:
        description: Gives the homes command
        default: true
      myplot.command.name:
        description: Gives the name command
        default: true
      myplot.command.give:
        description: Gives the give command
        default: true
      myplot.command.warp:
        description: Gives the warp command
        default: true
  myplot.admin:
    description: Grant administrator powers
    default: op
    children:
      myplot.admin.clear:
        description: Allow clear command on every plot
        default: op
      myplot.admin.dispose:
        description: Allow dispose command on every plot
        default: op
      myplot.admin.reset:
        description: Allow reset command on every plot
        default: op
      myplot.admin.addhelper:
        description: Allow addhelper command on every plot
        default: op
      myplot.admin.removehelper:
        description: Allow removehelper command on every plot
        default: op
      myplot.admin.build:
        description: Allow player to build outside his own plots
        default: op
        children:
          myplot.admin.build.plot:
            description: Allow player to build on all plots
            default: op
          myplot.admin.build.road:
            description: Allow player to build on the road
            default: op
      myplot.admin.name:
        description: Allows player to change the name of every plot
        default: op
      myplot.admin.warp:
        description: Allow player to warp to unclaimed plots
        default: op
  myplot.claimplots:
    description: Allows players to claim X plots
    default: false
    children:
      myplot.claimplots.2:
        description: Allow player to claim 2 plots
        default: true
      myplot.claimplots.unlimited:
        description: Allow player to claim unlimited plots
        default: op
