name: MyPlot
main: MyPlot\MyPlot
version: 1.9.0
api:
- 3.4.0
authors:
- Wiez
- Exxarion
- jasonwynn10
description: "Plots and Protection Plugin for PocketMine-MP Servers"
load: STARTUP
softdepend:
- EconomyAPI
- DEVirion
- WorldStyler
- EasyCommandAutofill
permissions:
  myplot.command:
    default: op
    children:
      myplot.command.help:
        default: true
      myplot.command.claim:
        default: true
      myplot.command.info:
        default: true
      myplot.command.generate:
        default: op
      myplot.command.addhelper:
        default: true
      myplot.command.removehelper:
        default: true
      myplot.command.denyplayer:
        default: true
      myplot.command.undenyplayer:
        default: true
      myplot.command.auto:
        default: true
      myplot.command.clear:
        default: true
      myplot.command.dispose:
        default: true
      myplot.command.reset:
        default: true
      myplot.command.biome:
        default: true
      myplot.command.biomes:
        default: true
      myplot.command.home:
        default: true
      myplot.command.homes:
        default: true
      myplot.command.name:
        default: true
      myplot.command.give:
        default: true
      myplot.command.warp:
        default: true
      myplot.command.done:
        default: true
      myplot.command.middle:
        default: true
      myplot.command.list:
        default: true
      myplot.command.pvp:
        default: true
      myplot.command.clone:
        default: true
      myplot.command.sell:
        default: true
      myplot.command.buy:
        default: true
  myplot.admin:
    default: op
    children:
      myplot.admin.clear:
        default: op
      myplot.admin.biome:
        default: op
      myplot.admin.biomes:
        defualt: op
      myplot.admin.dispose:
        default: op
      myplot.admin.reset:
        default: op
      myplot.admin.addhelper:
        default: op
      myplot.admin.removehelper:
        default: op
      myplot.admin.denyplayer:
        default: op
        children:
          myplot.admin.denyplayer.bypass:
            default: op
      myplot.admin.undenyplayer:
        default: op
      myplot.admin.build:
        default: op
        children:
          myplot.admin.build.plot:
            default: op
          myplot.admin.build.road:
            default: op
      myplot.admin.name:
        default: op
      myplot.admin.warp:
        default: op
      myplot.admin.done:
        default: op
      myplot.admin.middle:
        default: true
      myplot.admin.list:
        default: op
      myplot.admin.pvp:
        default: op
        children:
          myplot.admin.pvp.bypass:
            default: op
      myplot.admin.clone:
        default: op
      myplot.admin.sell:
        default: op
      myplot.admin.buy:
        default: op
  myplot.claimplots:
    default: op
    children:
      myplot.claimplots.2:
        default: true
      myplot.claimplots.unlimited:
        default: op
